build:
  image: clickable/ci-20.04-armhf
  except:
    - tags
  script:
    - CLICKABLE_FRAMEWORK=ubuntu-sdk-20.04 clickable build --clean --skip-review
  artifacts:
    paths:
      - build/*/app/*.click
    expire_in: 1 week
